#pragma once

// This file is generated by tools/import_fontawesome.py.
// Do not edit manually.

#include <string_view>

namespace DUIIcons::FontAwesome {

  namespace Solid {
    inline constexpr std::string_view ArrowsLeftRightToLine =
      "icons/fontawesome/solid/arrows-left-right-to-line.svg";

    inline constexpr std::string_view CircleExclamation =
      "icons/fontawesome/solid/circle-exclamation.svg";

    inline constexpr std::string_view CircleInfo =
      "icons/fontawesome/solid/circle-info.svg";

    inline constexpr std::string_view CircleQuestion =
      "icons/fontawesome/solid/circle-question.svg";

    inline constexpr std::string_view File =
      "icons/fontawesome/solid/file.svg";

    inline constexpr std::string_view Folder =
      "icons/fontawesome/solid/folder.svg";

    inline constexpr std::string_view Gear =
      "icons/fontawesome/solid/gear.svg";

    inline constexpr std::string_view Music =
      "icons/fontawesome/solid/music.svg";

    inline constexpr std::string_view Pause =
      "icons/fontawesome/solid/pause.svg";

    inline constexpr std::string_view Play =
      "icons/fontawesome/solid/play.svg";

    inline constexpr std::string_view Plus =
      "icons/fontawesome/solid/plus.svg";

    inline constexpr std::string_view Slash =
      "icons/fontawesome/solid/slash.svg";

    inline constexpr std::string_view Sliders =
      "icons/fontawesome/solid/sliders.svg";

    inline constexpr std::string_view Stop =
      "icons/fontawesome/solid/stop.svg";

    inline constexpr std::string_view TriangleExclamation =
      "icons/fontawesome/solid/triangle-exclamation.svg";

    inline constexpr std::string_view Xmark =
      "icons/fontawesome/solid/xmark.svg";

  }

  namespace Regular {
    inline constexpr std::string_view CircleQuestion =
      "icons/fontawesome/regular/circle-question.svg";

    inline constexpr std::string_view File =
      "icons/fontawesome/regular/file.svg";

    inline constexpr std::string_view Folder =
      "icons/fontawesome/regular/folder.svg";

  }

  namespace Brands {
    inline constexpr std::string_view Github =
      "icons/fontawesome/brands/github.svg";

  }

}
