#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd -- "$CONFIG_DIR/.." && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPTS_DIR/.." && pwd)"
# shellcheck source=scripts/lib/paths.sh
source "$CONFIG_DIR/paths.sh"
OLD_BUILD_TOOLS_DIR="$PROJECT_ROOT/old_build_tools"

APP_NAME="Synthem"
BUNDLE_ID="com.codelmao.synthem"

BUILD_DIR_IOS="$PROJECT_ROOT/$BUILD_IOS_OBJ_DIR"
BUILD_DIR_IOS_PACKAGE="$PROJECT_ROOT/$BUILD_IOS_PACKAGE_DIR"
BUILD_DIR_MACOS="$PROJECT_ROOT/$BUILD_MACOS_DIR"
BUILD_DIR_MACOS_PACKAGE="$PROJECT_ROOT/$BUILD_MACOS_PACKAGE_DIR"
BUILD_DIR_LINUX="$PROJECT_ROOT/$BUILD_LINUX_DIR"
BUILD_DIR_WINDOWS="$PROJECT_ROOT/$BUILD_WINDOWS_DIR"
BUILD_DIR_FULL_PACKAGE="$PROJECT_ROOT/$BUILD_FULL_PACKAGE_DIR"
BUILD_DIR_ICONS="$PROJECT_ROOT/$BUILD_ICONS_DIR"
BUILD_DIR_TESTS="$PROJECT_ROOT/$BUILD_TESTS_DIR"

IOS_IPA_PATH="$BUILD_DIR_IOS_PACKAGE/${APP_NAME}.ipa"
IOS_RAWEXEC_PATH="$BUILD_DIR_IOS_PACKAGE/${APP_NAME}"
IOS_APP_DIR="$BUILD_DIR_IOS_PACKAGE/Payload/${APP_NAME}.app"

MACOS_APP_PATH="$BUILD_DIR_MACOS_PACKAGE/${APP_NAME}.app"
MACOS_DMG_HFS_PATH="$BUILD_DIR_MACOS_PACKAGE/${APP_NAME}-macOS.hfs"
MACOS_DMG_PATH="$BUILD_DIR_MACOS_PACKAGE/${APP_NAME}.dmg"
MACOS_ICNS_PATH="$BUILD_DIR_ICONS/macos/${APP_NAME}.icns"

RESOURCE_DIR="$PROJECT_ROOT/resources"
ICON_SVG_PATH="$RESOURCE_DIR/icon.svg"
FONT_DIR="$RESOURCE_DIR/fonts"

IOS_TOOLCHAIN_BIN="/home/code/procursus/cctools-port/usage_examples/ios_toolchain/target/bin"
MACOS_TOOLCHAIN_BIN="/home/code/procursus/cctools-port/usage_examples/macos_toolchain/target/bin"
IOS_LDID_BIN="/home/code/ldid/ldid"
MACOS_LDID_BIN="$MACOS_TOOLCHAIN_BIN/ldid"

SYNTHEM_DEFAULT_MODE="release"
SYNTHEM_DEFAULT_TARGET="all"
SYNTHEM_DEFAULT_INSTALL=1
SYNTHEM_DEFAULT_DMG=0
SYNTHEM_DEFAULT_CLEAN=0

if command -v nproc >/dev/null 2>&1; then
  SYNTHEM_DEFAULT_JOBS="$(nproc)"
else
  SYNTHEM_DEFAULT_JOBS=4
fi

# Runtime options (overridable in scripts/synthem.sh parsing).
SYNTHEM_MODE="${SYNTHEM_DEFAULT_MODE}"
SYNTHEM_JOBS="${SYNTHEM_DEFAULT_JOBS}"
SYNTHEM_DO_INSTALL="${SYNTHEM_DEFAULT_INSTALL}"
SYNTHEM_DO_DMG="${SYNTHEM_DEFAULT_DMG}"
SYNTHEM_DO_CLEAN="${SYNTHEM_DEFAULT_CLEAN}"


# get the electron rcedit windows binary from:
# https://github.com/electron/rcedit/releases
WINDOWS_RCEDIT_BIN="${WINDOWS_RCEDIT_BIN:-$PROJECT_ROOT/scripts/tools/rcedit-x64.exe}"