#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import shutil
from dataclasses import dataclass
from pathlib import Path


DEFAULT_SOURCE_ROOT = Path("/home/code/font-awesome/svgs")
DEFAULT_DEST_ROOT = Path("resources/icons/fontawesome")
DEFAULT_HEADER_OUT = Path("directui/graphics/svg/FontAwesomeIcons.h")

STYLES = {
    "solid": "Solid",
    "regular": "Regular",
    "brands": "Brands",
}


@dataclass(frozen=True)
class IconEntry:
    style: str
    cpp_namespace: str
    cpp_name: str
    filename: str
    source_path: Path
    dest_path: Path
    resource_path: str


def to_cpp_identifier(icon_name: str) -> str:
    stem = Path(icon_name).stem

    # xmark -> Xmark, arrow-left -> ArrowLeft
    parts = re.split(r"[-_\s]+", stem)
    name = "".join(part[:1].upper() + part[1:] for part in parts if part)

    # C++ identifiers cannot start with a number.
    if name and name[0].isdigit():
        name = "Icon" + name

    # Last-resort safety.
    name = re.sub(r"[^A-Za-z0-9_]", "", name)

    if not name:
        name = "UnnamedIcon"

    return name


def normalize_icon_name(name: str) -> str:
    name = name.strip()

    if not name:
        return ""

    if name.endswith(".svg"):
        name = name[:-4]

    return name


def load_requested_icons(path: Path) -> list[str]:
    if not path.exists():
        raise FileNotFoundError(f"Icon list not found: {path}")

    icons: list[str] = []

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()

        if not line or line.startswith("#"):
            continue

        icons.append(normalize_icon_name(line))

    return icons


def discover_icons(
        source_root: Path,
        dest_root: Path,
        selected_icons: set[str] | None,
        include_all: bool,
) -> list[IconEntry]:
    entries: list[IconEntry] = []

    for style, cpp_namespace in STYLES.items():
        style_dir = source_root / style

        if not style_dir.exists():
            continue

        for source_path in sorted(style_dir.glob("*.svg")):
            icon_stem = source_path.stem

            if not include_all and selected_icons is not None:
                if icon_stem not in selected_icons:
                    continue

            filename = source_path.name
            cpp_name = to_cpp_identifier(filename)
            dest_path = dest_root / style / filename
            resource_path = f"icons/fontawesome/{style}/{filename}"

            entries.append(
                IconEntry(
                    style=style,
                    cpp_namespace=cpp_namespace,
                    cpp_name=cpp_name,
                    filename=filename,
                    source_path=source_path,
                    dest_path=dest_path,
                    resource_path=resource_path,
                )
            )

    return entries


def copy_icons(entries: list[IconEntry], dry_run: bool) -> None:
    for entry in entries:
        if dry_run:
            print(f"[copy] {entry.source_path} -> {entry.dest_path}")
            continue

        entry.dest_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(entry.source_path, entry.dest_path)


def generate_header(entries: list[IconEntry], header_out: Path, dry_run: bool) -> None:
    grouped: dict[str, list[IconEntry]] = {}

    for entry in entries:
        grouped.setdefault(entry.cpp_namespace, []).append(entry)

    lines: list[str] = [
        "#pragma once",
        "",
        "// This file is generated by tools/import_fontawesome.py.",
        "// Do not edit manually.",
        "",
        "#include <string_view>",
        "",
        "namespace DUIIcons::FontAwesome {",
        "",
    ]

    for namespace in ("Solid", "Regular", "Brands"):
        style_entries = grouped.get(namespace, [])

        if not style_entries:
            continue

        lines.append(f"  namespace {namespace} {{")

        used_names: dict[str, int] = {}

        for entry in style_entries:
            cpp_name = entry.cpp_name

            # Avoid rare name collisions cleanly.
            count = used_names.get(cpp_name, 0)
            used_names[cpp_name] = count + 1

            if count > 0:
                cpp_name = f"{cpp_name}{count + 1}"

            lines.append(f"    inline constexpr std::string_view {cpp_name} =")
            lines.append(f"      \"{entry.resource_path}\";")
            lines.append("")

        lines.append("  }")
        lines.append("")

    lines.append("}")
    lines.append("")

    text = "\n".join(lines)

    if dry_run:
        print(f"[write] {header_out}")
        print(text)
        return

    header_out.parent.mkdir(parents=True, exist_ok=True)
    header_out.write_text(text, encoding="utf-8")


def list_icons(source_root: Path, query: str | None) -> None:
    query_lower = query.lower() if query else None

    for style in STYLES:
        style_dir = source_root / style

        if not style_dir.exists():
            continue

        print(f"\n[{style}]")

        count = 0

        for svg in sorted(style_dir.glob("*.svg")):
            name = svg.stem

            if query_lower and query_lower not in name.lower():
                continue

            print(f"  {name}")
            count += 1

        if count == 0:
            print("  no matches")


def write_example_list(path: Path) -> None:
    example = """# Font Awesome icons to import.
# One icon name per line, without .svg.
# The script searches solid/regular/brands and copies matching files.

play
pause
stop
gear
music
wave-square
folder
file
plus
xmark
chevron-left
chevron-right
sliders
heart
github
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(example, encoding="utf-8")
    print(f"Wrote example icon list: {path}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Import selected Font Awesome SVGs and generate a C++ icon header."
    )

    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE_ROOT,
        help=f"Font Awesome svgs folder. Default: {DEFAULT_SOURCE_ROOT}",
    )

    parser.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_DEST_ROOT,
        help=f"Destination resource folder. Default: {DEFAULT_DEST_ROOT}",
    )

    parser.add_argument(
        "--header",
        type=Path,
        default=DEFAULT_HEADER_OUT,
        help=f"Generated C++ header path. Default: {DEFAULT_HEADER_OUT}",
    )

    parser.add_argument(
        "--icons",
        type=Path,
        default=Path("tools/fontawesome-icons.txt"),
        help="Text file containing icon names to import.",
    )

    parser.add_argument(
        "--all",
        action="store_true",
        help="Import every SVG from solid/regular/brands.",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen without copying/writing files.",
    )

    parser.add_argument(
        "--list",
        action="store_true",
        help="List available icons instead of importing.",
    )

    parser.add_argument(
        "--query",
        type=str,
        default=None,
        help="Filter --list output, e.g. --query arrow.",
    )

    parser.add_argument(
        "--init-list",
        action="store_true",
        help="Write an example tools/fontawesome-icons.txt file.",
    )

    args = parser.parse_args()

    if args.init_list:
        write_example_list(args.icons)
        return 0

    if args.list:
        list_icons(args.source, args.query)
        return 0

    if not args.source.exists():
        print(f"Source folder does not exist: {args.source}")
        return 1

    selected_icons: set[str] | None = None

    if not args.all:
        requested = load_requested_icons(args.icons)
        selected_icons = set(requested)

        if not selected_icons:
            print(f"No icons listed in {args.icons}")
            return 1

    entries = discover_icons(
        source_root=args.source,
        dest_root=args.dest,
        selected_icons=selected_icons,
        include_all=args.all,
    )

    if not entries:
        print("No icons matched.")
        return 1

    if selected_icons is not None:
        found_names = {Path(entry.filename).stem for entry in entries}
        missing = sorted(selected_icons - found_names)

        if missing:
            print("Missing requested icons:")
            for name in missing:
                print(f"  {name}")
            print("Continuing with icons that were found.\n")

    copy_icons(entries, dry_run=args.dry_run)
    generate_header(entries, args.header, dry_run=args.dry_run)

    print(f"Imported {len(entries)} icon file(s).")
    print(f"Destination: {args.dest}")
    print(f"Header: {args.header}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())